#!/bin/python3

subjects = ["physics", "calculus", "poetry", "history"]

grades = ["98" , "97", "85", "88"]

gradebook = [

[subjects[0],grades[0]],

[subjects[1],grades[1]],

[subjects[2],grades[2]],

[subjects[3],grades[3]]

]

print (gradebook)

subjects.append("computer science")

grades.append("100")

gradebook.append([subjects[4],grades[4]])

print (gradebook)

gradebook.append(["visual arts",93])

print (gradebook)

gradebook[-1][-1]=98
print (gradebook)

gradebook[2].remove('85')

gradebook[2].append("Pass")

print (gradebook)

last_semester_gradebook=[]

full_gradebook=(gradebook)+(last_semester_gradebook)

print(full_gradebook)


